

echo "=== Morph固有カラム可視化 (raw) ==="
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "BCL6 FISH"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "MYC FISH"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "BCL2 FISH"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "LDH"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "ECOG PS"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "Stage"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "IPI Risk Group"

echo "=== Morph共通カラム可視化 (raw) ==="
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "Age"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "MYC IHC"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "BCL2 IHC"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "BCL6 IHC"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "CD10 IHC"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "MUM1 IHC"
uv run python -m dlbcl.cluster visualize --dataset morph --noshow --target "HANS"

echo "=== Patho2固有カラム可視化 (raw) ==="
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "EBV"

echo "=== Patho2共通カラム可視化 (raw) ==="
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "Age"
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "MYC IHC"
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "BCL2 IHC"
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "BCL6 IHC"
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "CD10 IHC"
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "MUM1 IHC"
uv run python -m dlbcl.cluster visualize --dataset patho2 --noshow --target "HANS"

echo "=== Merged共通カラム可視化 (raw) ==="
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "Age"
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "MYC IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "BCL2 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "BCL6 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "CD10 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "MUM1 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --noshow --target "HANS"

echo "=== Combat補正版 Merged共通カラム可視化 ==="

uv run python -m dlbcl.cluster visualize --dataset merged --use-combat --noshow --target "MYC IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --use-combat --noshow --target "BCL2 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --use-combat --noshow --target "BCL6 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --use-combat --noshow --target "CD10 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --use-combat --noshow --target "MUM1 IHC"
uv run python -m dlbcl.cluster visualize --dataset merged --use-combat --noshow --target "HANS"

echo "=== 全可視化完了 ==="
echo "出力ディレクトリ:"
echo "- out/raw/morph/ (固有+共通カラム)"
echo "- out/raw/patho2/ (固有+共通カラム)"
echo "- out/raw/merged/ (共通カラム)"
echo "- out/combat/merged/ (Combat補正版共通カラム)"
